import type { Metadata } from "next";
import {Open_Sans }from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/ui/providers/theme-provider"; 

const font = Open_Sans({subsets: ['latin']})

export const metadata: Metadata = {
  title: "DiscordX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider  afterSignOutUrl="/">
      <html lang="en"suppressHydrationWarning>
        <body
          className={font.className}>
            <ThemeProvider
              attribute="class"
              defaultTheme="light"
              storageKey="discord-theme"
            >
            {children}
            </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
